# Config file for automatic testing at travis-ci.org

# Containerized builds
sudo: false

language: python

python:
  - "3.4"
  - "2.7"
#  - "pypy" # need pypy>2.6

install:
  - pip install -r dev-requirements.txt
  - pip install -U .

before_script:
  - flake8 .

script: py.test -s -v
